#!/usr/bin/env bash

set -euo pipefail

# ==============================================================================
# GENERIC DATABASE PROVISIONING ENGINE
#
# This script executes a service team's database initialization script against
# an already-running database engine.
#
# Responsibilities:
#
#   1. Load Core runtime configuration from the local .env file.
#   2. Validate the service team's configuration file.
#   3. Validate the service team's initialization script.
#   4. Read database metadata from the service configuration.
#   5. Retrieve service credentials from AWS Secrets Manager.
#   6. Retrieve the Core administrative credential when required.
#   7. Determine the correct database engine/container.
#   8. Execute the initialization script against that database engine.
#   9. Clear plaintext credential variables after execution.
#
# This script intentionally does NOT:
#
#   - create EC2 instances
#   - install Docker
#   - generate docker-compose.yml
#   - pull Docker images
#   - start database containers
#   - create AWS Secrets Manager secrets
#   - contain static AWS credentials
#
# Database deployment is handled by update.sh.
#
#
# RUNTIME CONFIGURATION
# ---------------------
#
# Core runtime configuration is loaded from:
#
#   <script-directory>/.env
#
# The .env file is generated by Terraform and contains values such as:
#
#   PROJECT_NAME
#   ENVIRONMENT
#   SERVICE_NAME
#   DATABASE_WORKSPACE
#   AWS_REGION
#   CORE_ROOT_SECRET_ARN
#   ECR_REGISTRY
#   ENABLE_ECR_ACCESS
#
# The actual database password MUST NOT be stored in .env.
# CORE_ROOT_SECRET_ARN is only the identifier of the AWS Secrets Manager
# secret containing the administrative database credential.
#
#
# SERVICE TEAM INPUTS
# -------------------
#
# Multiple service teams share this provisioning engine.
#
# Therefore the service team MUST explicitly provide both:
#
#   1. Its configuration file
#   2. Its initialization script
#
# Usage:
#
#   provision.sh <service_config> <initialization_script>
#
# Example:
#
#   ./provision.sh \
#       configs/orders.config \
#       inits/orders.init
#
# When relative paths are supplied, they are resolved relative to
# DATABASE_WORKSPACE.
#
# Expected workspace structure:
#
#   /opt/<project>/<service>/
#
#   ├── .env
#   ├── configs/
#   │   ├── orders.config
#   │   ├── payments.config
#   │   └── users.config
#   │
#   └── inits/
#       ├── orders.init
#       ├── payments.init
#       └── users.init
#
# ==============================================================================
# SCRIPT LOCATION
# ==============================================================================

SCRIPT_DIR="$(
  cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1
  pwd
)"


# ==============================================================================
# CORE ENVIRONMENT CONFIGURATION
#
# .env is expected to live beside this script.
#
# We deliberately load the file ourselves instead of requiring callers to
# export DATABASE_WORKSPACE, AWS_REGION, or CORE_ROOT_SECRET_ARN.
# ==============================================================================

ENV_FILE="${SCRIPT_DIR}/.env"


if [[ ! -f "${ENV_FILE}" ]]; then

  echo "ERROR: Required Core environment file was not found:"
  echo "       ${ENV_FILE}"

  exit 1

fi


# Export variables loaded from .env so AWS CLI and child processes can use them.
set -a
# shellcheck disable=SC1090  # the path is the host's workspace, known only at run time
source "${ENV_FILE}"
set +a


# ==============================================================================
# VALIDATE CORE ENVIRONMENT CONFIGURATION
# ==============================================================================

if [[ -z "${DATABASE_WORKSPACE:-}" ]]; then

  echo "ERROR: DATABASE_WORKSPACE is not configured in .env."

  exit 1

fi


if [[ -z "${AWS_REGION:-}" ]]; then

  echo "ERROR: AWS_REGION is not configured in .env."

  exit 1

fi


if [[ -z "${CORE_ROOT_SECRET_ARN:-}" ]]; then

  echo "ERROR: CORE_ROOT_SECRET_ARN is not configured in .env."

  exit 1

fi


# ==============================================================================
# SCRIPT ARGUMENTS
#
# Both arguments are mandatory because this provisioning engine is shared by
# multiple service teams.
# ==============================================================================

if [[ $# -lt 2 || $# -gt 3 ]]; then

  echo "ERROR: Invalid arguments."

  echo
  echo "Usage:"
  echo "  ${0} <service_config> <initialization_script> [admin|service]"
  echo
  echo "  admin   (the default) runs the script as the engine's administrator."
  echo "          Core's own provisioning scripts run this way: creating a"
  echo "          database and a role needs administrative rights."
  echo
  echo "  service runs the script as the SERVICE's own user, on the service's own"
  echo "          database. A service may supply extra SQL of its own, and it must"
  echo "          not run that as the administrator: that would be full control of"
  echo "          every other service's database on the same engine."

  echo
  echo "Example:"
  echo "  ${0} \\"
  echo "    /opt/project/sevice-name/configs/orders.config \\"
  echo "    /opt/project/sevice-name/inits/orders.init"

  exit 1

fi


CONFIG_FILE="$1"
INIT_SCRIPT="$2"
RUN_AS="${3:-admin}"

if [[ "${RUN_AS}" != "admin" && "${RUN_AS}" != "service" ]]; then

  echo "ERROR: the third argument must be 'admin' or 'service', not '${RUN_AS}'."

  exit 1

fi



# ==============================================================================
# VALIDATE DATABASE WORKSPACE
# ==============================================================================

if [[ ! -d "${DATABASE_WORKSPACE}" ]]; then

  echo "ERROR: Database workspace does not exist:"
  echo "       ${DATABASE_WORKSPACE}"

  exit 1

fi

# ==============================================================================
# DEFINE SERVICE TEAM DIRECTORIES
#
# The Core database workspace is shared by multiple service teams.
#
# configs/
#   Contains service-specific configuration files.
#
# inits/
#   Contains service-specific SQL/NoSQL initialization scripts.
# ==============================================================================

CONFIGS_DIR="${DATABASE_WORKSPACE}/configs"

INITS_DIR="${DATABASE_WORKSPACE}/inits"


if [[ ! -d "${CONFIGS_DIR}" ]]; then

  echo "ERROR: Service configuration directory does not exist:"
  echo "       ${CONFIGS_DIR}"

  exit 1

fi


if [[ ! -d "${INITS_DIR}" ]]; then

  echo "ERROR: Service initialization directory does not exist:"
  echo "       ${INITS_DIR}"

  exit 1

fi


# ==============================================================================
# VALIDATE SERVICE CONFIGURATION
# ==============================================================================

if [[ ! -s "${CONFIG_FILE}" ]]; then

  echo "ERROR: Service configuration file does not exist or is empty:"
  echo "       ${CONFIG_FILE}"

  exit 1

fi


# ==============================================================================
# VALIDATE INITIALIZATION SCRIPT
# ==============================================================================

if [[ ! -s "${INIT_SCRIPT}" ]]; then

  echo "ERROR: Initialization script does not exist or is empty:"
  echo "       ${INIT_SCRIPT}"

  exit 1

fi


# ==============================================================================
# RESOLVE FILE PATHS
#
# Resolve both supplied files to their canonical filesystem paths.
#
# This prevents callers from bypassing the configs/ and inits/ directory
# boundaries using paths such as:
#
#   configs/../some-other-file
#
# The service configuration must remain inside configs/.
# The initialization script must remain inside inits/.
# ==============================================================================

RESOLVED_CONFIG_FILE="$(
  readlink -f "${CONFIG_FILE}"
)"

RESOLVED_INIT_SCRIPT="$(
  readlink -f "${INIT_SCRIPT}"
)"

RESOLVED_CONFIGS_DIR="$(
  readlink -f "${CONFIGS_DIR}"
)"

RESOLVED_INITS_DIR="$(
  readlink -f "${INITS_DIR}"
)"

RESOLVED_WORKSPACE="$(
  readlink -f "${DATABASE_WORKSPACE}"
)"


# ==============================================================================
# ENFORCE CONFIGURATION DIRECTORY BOUNDARY
# ==============================================================================

case "${RESOLVED_CONFIG_FILE}" in

  "${RESOLVED_CONFIGS_DIR}"/*)
    ;;

  *)
    echo "ERROR: Service configuration must be located inside:"
    echo "       ${RESOLVED_CONFIGS_DIR}"
    echo
    echo "Received:"
    echo "       ${RESOLVED_CONFIG_FILE}"

    exit 1

esac


# ==============================================================================
# ENFORCE INITIALIZATION DIRECTORY BOUNDARY
# ==============================================================================

# Two places are legitimate: the inits directory, where a service's own script is
# written, and the workspace itself, which holds core's per-engine provisioning
# scripts (fetched and checksum-verified with the rest of the platform scripts).
# Anything else is a path that escaped, and is refused.
case "${RESOLVED_INIT_SCRIPT}" in

  "${RESOLVED_INITS_DIR}"/* | "${RESOLVED_WORKSPACE}"/provision-*)
    ;;

  *)
    echo "ERROR: Initialization script must be one of core's provisioning scripts"
    echo "       (${RESOLVED_WORKSPACE}/provision-*), or a file inside:"
    echo "       ${RESOLVED_INITS_DIR}"
    echo
    echo "Received:"
    echo "       ${RESOLVED_INIT_SCRIPT}"

    exit 1

esac


# ==============================================================================
# USE CANONICAL PATHS AFTER VALIDATION
# ==============================================================================

CONFIG_FILE="${RESOLVED_CONFIG_FILE}"

INIT_SCRIPT="${RESOLVED_INIT_SCRIPT}"


# ==============================================================================
# VALIDATE REQUIRED UTILITIES
# ==============================================================================

for command in jq aws docker; do

  if ! command -v "${command}" >/dev/null 2>&1; then

    echo "ERROR: Required command is not installed:"
    echo "       ${command}"

    exit 1

  fi

done


# ==============================================================================
# READ SERVICE DATABASE METADATA
#
# Expected service configuration structure:
#
# {
#   "service_name": "orders",
#   "database_engine": "postgres",
#   "database_secrets_arn": "arn:aws:secretsmanager:...",
#   "secret_mappings": {
#     "db_key": "database",
#     "user_key": "username",
#     "pass_key": "password"
#   }
# }
#
# ==============================================================================

SERVICE="$(
  jq -er '.service_name' "${CONFIG_FILE}"
)"


ENGINE="$(
  jq -er '.database_engine' "${CONFIG_FILE}"
)"


SECRETS_ARN="$(
  jq -er '.database_secrets_arn' "${CONFIG_FILE}"
)"


MAP_DB="$(
  jq -er '.secret_mappings.db_key' "${CONFIG_FILE}"
)"


MAP_USER="$(
  jq -er '.secret_mappings.user_key' "${CONFIG_FILE}"
)"


MAP_PASS="$(
  jq -er '.secret_mappings.pass_key' "${CONFIG_FILE}"
)"


# ==============================================================================
# VALIDATE SERVICE METADATA
# ==============================================================================

if [[ -z "${SERVICE}" ]]; then

  echo "ERROR: service_name cannot be empty."

  exit 1

fi


if [[ -z "${ENGINE}" ]]; then

  echo "ERROR: database_engine cannot be empty."

  exit 1

fi


if [[ -z "${SECRETS_ARN}" ]]; then

  echo "ERROR: database_secrets_arn cannot be empty."

  exit 1

fi


if [[ -z "${MAP_DB}" || -z "${MAP_USER}" || -z "${MAP_PASS}" ]]; then

  echo "ERROR: secret_mappings must define:"
  echo "       db_key"
  echo "       user_key"
  echo "       pass_key"

  exit 1

fi


# ==============================================================================
# DETERMINE DATABASE CONTAINER
#
# The platforms team deploys every engine as its own Docker Compose project
# named db-<engine> (see update.sh, which owns that convention). Docker labels
# each container with the project it belongs to, so the running container is
# found by asking Docker for it -- this script keeps no engine map of its own
# that could drift out of sync with what update.sh actually deployed.
#
# ENGINE comes from a service-supplied config file, so it is validated before
# it is used in a Docker filter.
# ==============================================================================

if ! [[ "${ENGINE}" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then

  echo "ERROR: database_engine '${ENGINE}' is not a valid engine name"
  echo "       (lowercase letters, digits and hyphens only)."

  exit 1

fi

COMPOSE_PROJECT="db-${ENGINE}"

DATABASE_CONTAINER="$(
  docker ps \
    --filter "label=com.docker.compose.project=${COMPOSE_PROJECT}" \
    --format '{{.Names}}' \
  | head -n 1 || true
)"

if [[ -z "${DATABASE_CONTAINER}" ]]; then

  echo "ERROR: No running container found for engine '${ENGINE}'"
  echo "       (Compose project ${COMPOSE_PROJECT})."
  echo
  echo "Confirm the engine is registered and active in database/registry.json"
  echo "and that update.sh has run since it was activated."

  exit 1

fi


# ==============================================================================
# VERIFY DATABASE CONTAINER
#
# update.sh should have already deployed the database workload.
#
# provision.sh deliberately does not start the database container itself.
# ==============================================================================

if ! docker container inspect "${DATABASE_CONTAINER}" >/dev/null 2>&1; then

  echo "ERROR: Database container is not present:"
  echo "       ${DATABASE_CONTAINER}"

  echo
  echo "Run update.sh before executing provision.sh."

  exit 1

fi


CONTAINER_RUNNING="$(
  docker inspect \
    --format '{{.State.Running}}' \
    "${DATABASE_CONTAINER}"
)"


if [[ "${CONTAINER_RUNNING}" != "true" ]]; then

  echo "ERROR: Database container exists but is not running:"
  echo "       ${DATABASE_CONTAINER}"

  exit 1

fi


# ==============================================================================
# CORE ADMINISTRATIVE CREDENTIAL
#
# The actual root password is never stored in .env.
#
# .env contains only:
#
#   CORE_ROOT_SECRET_ARN
#
# The identifier is used to retrieve the actual credential from AWS Secrets
# Manager at runtime.
#
# If DB_ROOT_PASSWORD has already been injected into the current process
# environment, we reuse it and avoid an unnecessary Secrets Manager request.
# ==============================================================================

if [[ -z "${DB_ROOT_PASSWORD:-}" ]]; then

  echo "Retrieving Core database administrative credential."

  CORE_PAYLOAD="$(
    aws secretsmanager get-secret-value \
      --region "${AWS_REGION}" \
      --secret-id "${CORE_ROOT_SECRET_ARN}" \
      --query 'SecretString' \
      --output text
  )"


  DB_ROOT_PASSWORD="$(
    jq -er '.root_password' <<< "${CORE_PAYLOAD}"
  )"


  if [[ -z "${DB_ROOT_PASSWORD}" ]]; then

    echo "ERROR: Core database administrative credential is empty."

    exit 1

  fi

  export DB_ROOT_PASSWORD

fi


# ==============================================================================
# SERVICE DATABASE CREDENTIALS
#
# Retrieve the service team's secret from AWS Secrets Manager.
# ==============================================================================

echo "Retrieving database credentials for service: ${SERVICE}"


TEAM_PAYLOAD="$(
  aws secretsmanager get-secret-value \
    --region "${AWS_REGION}" \
    --secret-id "${SECRETS_ARN}" \
    --query 'SecretString' \
    --output text
)"


TRUE_DB="$(
  jq -er ".${MAP_DB}" <<< "${TEAM_PAYLOAD}"
)"


TRUE_USER="$(
  jq -er ".${MAP_USER}" <<< "${TEAM_PAYLOAD}"
)"


TRUE_PASS="$(
  jq -er ".${MAP_PASS}" <<< "${TEAM_PAYLOAD}"
)"


# ==============================================================================
# VALIDATE SERVICE CREDENTIALS
# ==============================================================================

if [[ -z "${TRUE_DB}" ]]; then

  echo "ERROR: Database name resolved to an empty value."

  exit 1

fi


if [[ -z "${TRUE_USER}" ]]; then

  echo "ERROR: Database username resolved to an empty value."

  exit 1

fi


if [[ -z "${TRUE_PASS}" ]]; then

  echo "ERROR: Database password resolved to an empty value."

  exit 1

fi


# ==============================================================================
# DATABASE PROVISIONING
# ==============================================================================

echo "============================================================"
echo "Starting database provisioning"
echo "Service:  ${SERVICE}"
echo "Engine:   ${ENGINE}"
echo "Database: ${TRUE_DB}"
echo "============================================================"


# ==============================================================================
# MYSQL
#
# The root password is passed via MYSQL_PWD, an environment variable set
# on the docker exec invocation itself (-e), not as a "-p<password>" CLI
# argument. mysql's own client explicitly warns that passing a password
# on the command line is insecure, since it stays visible in that
# process's argument list (readable via `ps`/`/proc/<pid>/cmdline`) for
# as long as the process runs. An environment variable lands in a
# different, narrower-exposure part of the process (its environment
# block, not its argv) -- the same protection MYSQL_PWD has always
# existed specifically to provide.
# ==============================================================================

# ==============================================================================
# VALIDATE THE RESOLVED CREDENTIALS
#
# They are about to be interpolated into SQL that the engine runs with full
# rights, so they are held to the alphabet core generates them from. A name
# carrying a quote could otherwise end a string and begin a statement of its own.
# ==============================================================================

if ! [[ "${TRUE_DB}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then

  echo "ERROR: the database name from the secret is not a plain identifier."

  exit 1

fi

if ! [[ "${TRUE_USER}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then

  echo "ERROR: the user name from the secret is not a plain identifier."

  exit 1

fi

if ! [[ "${TRUE_PASS}" =~ ^[A-Za-z0-9._-]+$ ]]; then

  echo "ERROR: the password from the secret contains characters that are not allowed."
  echo "       Core generates passwords from letters, digits and -_. precisely so"
  echo "       that they are safe here and in the env files they pass through."

  exit 1

fi


# ==============================================================================
# RUN THE SCRIPT
#
# admin   core's own provisioning script, which creates the database and the role.
# service the service's own extra script, run as the service's user on the
#         service's own database, so it cannot reach another service's data.
#
# ON_ERROR_STOP makes psql exit non-zero on the first failed statement; without it
# a failed provisioning would look successful.
# ==============================================================================

if [[ "${ENGINE}" == "mysql" ]]; then

  if [[ "${RUN_AS}" == "admin" ]]; then

    echo "Executing MySQL initialization script as root."

    (
      echo "SET @target_db='${TRUE_DB}';"
      echo "SET @target_user='${TRUE_USER}';"
      echo "SET @target_pass='${TRUE_PASS}';"
      cat "${INIT_SCRIPT}"
    ) | docker exec \
        -i \
        -e MYSQL_PWD="${DB_ROOT_PASSWORD}" \
        "${DATABASE_CONTAINER}" \
        mysql \
        -uroot

  else

    echo "Executing MySQL script as ${TRUE_USER} on ${TRUE_DB}."

    docker exec \
        -i \
        -e MYSQL_PWD="${TRUE_PASS}" \
        "${DATABASE_CONTAINER}" \
        mysql \
        -u"${TRUE_USER}" \
        -D"${TRUE_DB}" < "${INIT_SCRIPT}"

  fi

elif [[ "${ENGINE}" == "postgres" ]]; then

  if [[ "${RUN_AS}" == "admin" ]]; then

    echo "Executing PostgreSQL initialization script as postgres."

    (
      echo "\\set target_db '${TRUE_DB}'"
      echo "\\set target_user '${TRUE_USER}'"
      echo "\\set target_pass '${TRUE_PASS}'"
      cat "${INIT_SCRIPT}"
    ) | docker exec \
        -i \
        "${DATABASE_CONTAINER}" \
        psql \
        -U postgres \
        -v ON_ERROR_STOP=1

  else

    echo "Executing PostgreSQL script as ${TRUE_USER} on ${TRUE_DB}."

    docker exec \
        -i \
        -e PGPASSWORD="${TRUE_PASS}" \
        "${DATABASE_CONTAINER}" \
        psql \
        -U "${TRUE_USER}" \
        -d "${TRUE_DB}" \
        -h 127.0.0.1 \
        -v ON_ERROR_STOP=1 < "${INIT_SCRIPT}"

  fi

elif [[ "${ENGINE}" == "mongodb" ]]; then

  if [[ "${RUN_AS}" == "admin" ]]; then

    echo "Executing MongoDB initialization script as the administrator."

    (
      echo "db.getSiblingDB('admin').auth('admin', process.env.MONGO_ROOT_PWD);"
      echo "const target_db = '${TRUE_DB}';"
      echo "const target_user = '${TRUE_USER}';"
      echo "const target_pass = '${TRUE_PASS}';"
      cat "${INIT_SCRIPT}"
    ) | docker exec \
        -i \
        -e MONGO_ROOT_PWD="${DB_ROOT_PASSWORD}" \
        "${DATABASE_CONTAINER}" \
        mongosh \
        --quiet

  else

    echo "Executing MongoDB script as ${TRUE_USER} on ${TRUE_DB}."

    docker exec \
        -i \
        "${DATABASE_CONTAINER}" \
        mongosh \
        --quiet \
        -u "${TRUE_USER}" \
        -p "${TRUE_PASS}" \
        --authenticationDatabase "${TRUE_DB}" \
        "${TRUE_DB}" < "${INIT_SCRIPT}"

  fi

else

  echo "ERROR: provision.sh has no initialization logic for engine:"
  echo "       ${ENGINE}"
  echo
  echo "Supported engines: mysql, postgres, mongodb."

  exit 1

fi


# ==============================================================================
# SUCCESS
# ==============================================================================

echo "============================================================"
echo "Database provisioning completed successfully."
echo "Service: ${SERVICE}"
echo "Engine:  ${ENGINE}"
echo "============================================================"


# ==============================================================================
# SECURITY CLEANUP
#
# Remove plaintext credentials from the current shell environment.
#
# Assigning an empty value and unsetting the variables minimizes their lifetime
# in the shell. It does not guarantee physical memory erasure.
# ==============================================================================

TRUE_DB=""
TRUE_USER=""
TRUE_PASS=""
TEAM_PAYLOAD=""
CORE_PAYLOAD=""
DB_ROOT_PASSWORD=""

unset TRUE_DB
unset TRUE_USER
unset TRUE_PASS
unset TEAM_PAYLOAD
unset CORE_PAYLOAD
unset DB_ROOT_PASSWORD

echo "Credential variables cleared from the current shell."